# Generated by Django 4.0.3 on 2022-03-10 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelList',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservationApp.hotellist')),
            ],
        ),
        migrations.CreateModel(
            name='GuestList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('res', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestInReservation', to='ReservationApp.reservationdetails')),
            ],
        ),
    ]
