# Generated by Django 4.0.3 on 2022-03-11 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0002_alter_reservationdetails_confirmation_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlist',
            name='first_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_first_name', message='First Name must be Alphabets', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='guestlist',
            name='last_name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_last_name', message='Last Name must be Alphabets', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='hotellist',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_hotel_name', message='Hotel Name must be Alphanumeric', regex='^[a-zA-Z0-9]*$')]),
        ),
    ]
