# Generated by Django 4.0.3 on 2022-03-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0003_alter_guestlist_first_name_alter_guestlist_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdetails',
            name='rooms_available',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
