# Generated by Django 4.0.3 on 2022-03-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservationApp', '0004_reservationdetails_rooms_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationdetails',
            name='rooms_available',
        ),
        migrations.AddField(
            model_name='hotellist',
            name='rooms_available',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
